# Generated by Django 6.0.3 on 2026-03-25 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_DB',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('message_created', models.DateTimeField(blank=True, null=True)),
                ('message_deleted', models.DateTimeField(blank=True, null=True)),
                ('message_topic', models.TextField()),
                ('message_text', models.TextField()),
                ('message_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
                ('message_recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message_DB',
                'verbose_name_plural': 'messages_DB',
            },
        ),
    ]
