# Generated by Django 6.0.3 on 2026-03-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_db', '0003_alter_message_db_message_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_db',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
