# Generated by Django 6.0.3 on 2026-03-19 15:18

import django.db.models.deletion
import file_db.storage
import file_db.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File_DB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(editable=False, storage=file_db.storage.ProtectedStorage(), upload_to=file_db.utils.upload_to_uuid7)),
                ('original_file_name', models.CharField(max_length=256)),
                ('file_size', models.PositiveBigIntegerField()),
                ('mimetype', models.CharField(max_length=256)),
                ('time_upload', models.DateTimeField(blank=True, null=True)),
                ('time_deleted', models.DateTimeField(blank=True, null=True)),
                ('tags', models.TextField(max_length=256)),
                ('access_customer', models.BooleanField()),
                ('access_staff', models.BooleanField()),
                ('access_super', models.BooleanField()),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File_DB',
                'verbose_name_plural': 'Files_DB',
            },
        ),
    ]
