# Generated by Django 6.0.3 on 2026-03-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_db',
            name='access_any',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file_db',
            name='access_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='file_db',
            name='access_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='file_db',
            name='access_super',
            field=models.BooleanField(default=False),
        ),
    ]
