# Generated by Django 6.0.3 on 2026-03-23 10:09

import file_db.models
import file_db.storage
import file_db.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_db', '0002_file_db_access_any_alter_file_db_access_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_db',
            name='access_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file_db',
            name='file',
            field=models.FileField(editable=False, storage=file_db.storage.ProtectedStorage(), upload_to=file_db.utils.upload_to_uuid7, validators=[file_db.models.validate_file_type]),
        ),
    ]
