# Generated by Django 6.0.3 on 2026-03-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_db', '0003_alter_file_db_access_staff_alter_file_db_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_db',
            name='tags',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
